version: '2'
services:
  cookie_pool_lite:
    build: .
    container_name: cookie_pool_lite
    restart: always
    ports:
      - "11006:11006"
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: "redis"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
